
import os
x="ok"
directory = "GeeksforGeeks"

# Parent Directory path
parent_dir = "D:\Software Development\project2\dirs"

# Path
path = os.path.join(parent_dir, directory,x)

# os.mkdir(path)
# print("Directory '% s' created" % directory)
newpath = path
if not os.path.exists(newpath):
    os.makedirs(newpath)
    print("Directory '% s' created" % directory)

print(path)
die=path+"\demofile3.txt"
f = open(die, "w")
f.write("Woops! I have deleted the content!")
f.close()

#open and read the file after the appending:
f = open(die, "r")
print(f.read())
f.close()